kubectl apply -f  livefeed-1-pricing-audjpy.yaml
kubectl apply -f  livefeed-1-pricing-audusd.yaml
kubectl apply -f  livefeed-1-pricing-eurchf.yaml
kubectl apply -f  livefeed-1-pricing-eurgbp.yaml
kubectl apply -f  livefeed-1-pricing-eurjpy.yaml
kubectl apply -f  livefeed-1-pricing-eurusd.yaml
kubectl apply -f  livefeed-1-pricing-gbpchf.yaml
kubectl apply -f  livefeed-1-pricing-gbpnzd.yaml
kubectl apply -f  livefeed-1-pricing-gbpusd.yaml
kubectl apply -f  livefeed-1-pricing-usdchf.yaml
kubectl apply -f  livefeed-1-pricing-usdjpy.yaml
kubectl apply -f  livefeed-1-signal.yaml
